### ISSUE TITLE
Why the Price for my order is zero

### ISSUE THREAD

**Issue by lenhhoxung86** [ericsomdahl/python-bittrex#103]
Hello, 
When I call function `get_open_orders()`, I can see all my orders returned.
However, the price for these orders is always zero.
For example:
```
{
	'success': True,
	'message': '',
	'result': [{
		'Opened': '2017-12-10T23:12:04.75',
		'QuantityRemaining': 554.73426096,
		'Exchange': 'BTC-OMG',
		'OrderUuid': 'xxxx',
		'Quantity': 554.73426096,
		'Limit': 0.001055,
		'Price': 0.0,
		'CancelInitiated': False,
		'CommissionPaid': 0.0,
		'PricePerUnit': None,
		'ImmediateOrCancel': False,
		'OrderType': 'LIMIT_SELL',
		'Uuid': None,
		'Closed': None,
		'Condition': 'NONE',
		'ConditionTarget': None,
		'IsConditional': False
	}, {
		'Opened': '2017-12-12T02:28:52.973',
		'QuantityRemaining': 213.82636656,
		'Exchange': 'BTC-MEME',
		'OrderUuid': 'xxxx',
		'Quantity': 213.82636656,
		'Limit': 9.8e-05,
		'Price': 0.0,
		'CancelInitiated': False,
		'CommissionPaid': 0.0,
		'PricePerUnit': None,
		'ImmediateOrCancel': False,
		'OrderType': 'LIMIT_SELL',
		'Uuid': None,
		'Closed': None,
		'Condition': 'NONE',
		'ConditionTarget': None,
		'IsConditional': False
	}]
}
```
How can I fix it?
Thanks.

**Comment by ericsomdahl** [comment]
Looks like they are regular Limit orders, and the Limit value is set in
both of those instances.

As a general rule this wrapper only acts as a passthrough for the data
coming back from Bittrex API endpoints.  There is one single helper method (
list_markets_by_currency) but the rest just relay what is received from the
remote server.

**Comment by slazarov** [comment]
In other words
```python
{
	'success': True,
	'message': '',
	'result': [{
		'Limit': this is the <limit> price you set initially,
                'PricePerUnit': the actual price the order got filled at (it might have been filled at a better price)
		'Price': Limit * PricePerUnit i.e total value,
	}]
}
```

**Comment by lenhhoxung86** [comment]
@slazarov So the field "Price" is set to zero as "PricePerUnit" is None, isn't it?
Additional question: What's the difference between "QuantityRemaining" and "Quantity"?
In the above orders, what's the unit of "554.73426096", is it OMG? 
Thanks.

**Comment by slazarov** [comment]
@Tiendh  until your order gets partially/fully filled,   
  

  
  
 `PricePerUnit` will stay as None and since   `Price` is a function of it it wil be 0.
  

  
 `Quantity` - the initial order quantity
  
 `QuantityRemaining` - if you put an order for 100 units of something and the opposite demand/supply for that ticker at that price is less than the 100 units, say only 50. Your   `QuantityRemaining` will be 50 while your   `Quantity` will be 100. Note that the order will be still active, but partially filled.
  

  
Unless you have 554 units of BTC, than it is OMG :).
  

  
In the finance world, the ticker quoting convention is usually like that:
  
X/Y - 1 unit of X buys/sells N units of Y
  
Example:
  
EUR/USD 1.20 - 1 EUR buys/sells 1.20 USD
  

  
Now in the case of Bittrex, they quote it in the opposite manner. So:
  
BTC/OMG translates to 1 OMG for N units of BTC.
  

  
Hope that was clear. My advice is to experiment with small trades to get the feel of it.
  

  
>

**Comment by lenhhoxung86** [comment]
Your advice has cleared my mind. Merci.
