### ISSUE TITLE
setting time in force in sell limit orders

### ISSUE THREAD

**Issue by 001gouthi** [ericsomdahl/python-bittrex#52]
how can i place a sell limit order which would be an immediate or cancel using the api?

**Comment by ericsomdahl** [comment]
Time in force parameters are part of the 2.0 API and we only support 1.1 at this time.

So the short answer is no, you cannot place the order as you specified.

The longer answer:
#35 specifies all of the endpoints that we know of but there is no actual documentation that I can find from Bittrex.  I am reluctant to code against an API that is under active development since there is a high risk of my time being wasted as I make changes against a moving target.

But I think there is some plumbing changes that should be made in order to support 1.1 and 2.0 together int he same codebase.  It seems both will be around for some time to come.  I am going to look into these changes soon

**Comment by ericsomdahl** [comment]
a branch has been started for the 2.0 API.  these calls will be supported when that is done.
